import hash_table
import library

myset1 = hash_table.HashSet("Chain", (33, 107))
myset2 = hash_table.HashSet("Linear", (33, 107))
myset3 = hash_table.HashSet("Double", (33, 10, 5, 107))

myset1.insert("Apple")
myset2.insert("Apple")
myset3.insert("Apple")
myset1.insert("Ganana")
myset2.insert("Ganana")
myset3.insert("Ganana")
myset1.insert("Apple")
myset2.insert("Apple")
myset3.insert("Apple")
myset1.insert("Ganana")
myset2.insert("Ganana")
myset3.insert("Ganana")

if not myset1.find("Apple"):
    print("Error: Apple not found in myset1")
if not myset2.find("Apple"):
    print("Error: Apple not found in myset2")
if not myset3.find("Apple"):
    print("Error: Apple not found in myset3")
    
if not myset1.find("Ganana"):
    print("Error: Ganana not found in myset1")
if not myset2.find("Ganana"):
    print("Error: Ganana not found in myset2")
if not myset3.find("Ganana"):
    print("Error: Ganana not found in myset3")

if myset1.find("orange"):
    print("Error: orange found in myset1")
if myset2.find("orange"):
    print("Error: orange found in myset2")
if myset3.find("orange"):
    print("Error: orange found in myset3")


print(myset1)
print(myset2)
print(myset3)

mymap1 = hash_table.HashMap("Chain", (33, 29))
mymap2 = hash_table.HashMap("Linear", (33, 29))
mymap3 = hash_table.HashMap("Double", (33, 10, 5, 29))

mymap1.insert(("Apple", 1))
mymap2.insert(("Apple", 1))
mymap3.insert(("Apple", 1))
mymap1.insert(("Banana", 3))
mymap2.insert(("Banana", 3))
mymap3.insert(("Banana", 3))
mymap1.insert(("Cherry", 4))
mymap2.insert(("Cherry", 4))
mymap3.insert(("Cherry", 4))
mymap1.insert(("Date", 5))
mymap2.insert(("Date", 5))
mymap3.insert(("Date", 5))
mymap1.insert(("Elderberry", 6))
mymap2.insert(("Elderberry", 6))
mymap3.insert(("Elderberry", 6))
mymap1.insert(("Fig", 7))
mymap2.insert(("Fig", 7))
mymap3.insert(("Fig", 7))
mymap1.insert(("Grape", 8))
mymap2.insert(("Grape", 8))
mymap3.insert(("Grape", 8))
mymap1.insert(("Honeydew", 9))
mymap2.insert(("Honeydew", 9))
mymap3.insert(("Honeydew", 9))
mymap1.insert(("Kiwi", 10))
mymap2.insert(("Kiwi", 10))
mymap3.insert(("Kiwi", 10))
mymap1.insert(("Lemon", 11))
mymap2.insert(("Lemon", 11))
mymap3.insert(("Lemon", 11))
mymap1.insert(("Mango", 12))
mymap2.insert(("Mango", 12))
mymap3.insert(("Mango", 12))
mymap1.insert(("Nectarine", 13))
mymap2.insert(("Nectarine", 13))
mymap3.insert(("Nectarine", 13))
mymap1.insert(("Orange", 14))
mymap2.insert(("Orange", 14))
mymap3.insert(("Orange", 14))
mymap1.insert(("Papaya", 15))
mymap2.insert(("Papaya", 15))
mymap3.insert(("Papaya", 15))
mymap1.insert(("Quince", 16))
mymap2.insert(("Quince", 16))
mymap3.insert(("Quince", 16))
mymap1.insert(("Raspberry", 17))
mymap2.insert(("Raspberry", 17))
mymap3.insert(("Raspberry", 17))
mymap1.insert(("Strawberry", 18))
mymap2.insert(("Strawberry", 18))
mymap3.insert(("Strawberry", 18))
mymap1.insert(("Tomato", 19))
mymap2.insert(("Tomato", 19))
mymap3.insert(("Tomato", 19))
mymap1.insert(("UgliFruit", 20))
mymap2.insert(("UgliFruit", 20))
mymap3.insert(("UgliFruit", 20))
mymap1.insert(("Vanilla", 21))
mymap2.insert(("Vanilla", 21))
mymap3.insert(("Vanilla", 21))
mymap1.insert(("Watermelon", 22))
mymap2.insert(("Watermelon", 22))
mymap3.insert(("Watermelon", 22))
mymap1.insert(("Xigua", 23))
mymap2.insert(("Xigua", 23))
mymap3.insert(("Xigua", 23))
mymap1.insert(("Yam", 24))
mymap2.insert(("Yam", 24))
mymap3.insert(("Yam", 24))
mymap1.insert(("Zucchini", 25))
mymap2.insert(("Zucchini", 25))
mymap3.insert(("Zucchini", 25))

print(mymap1)
print(mymap2)
print(mymap3)

jobs = library.JGBLibrary("Jobs", (33, 15))
# print(jobs.hh)